<?php
return [
    'AI2D' => [
        'smtp_host' => 'smtp.gmail.com',
        'smtp_username' => 'XXX@mail.fr',
        'smtp_password' => ' ',
        'smtp_secure' => 'ssl',
        'smtp_port' => 465,
    ],
    'BIM' => [
        'smtp_host' => 'smtp.gmail.com',
        'smtp_username' => 'XXX@mail.fr',
        'smtp_password' => ' ',
        'smtp_secure' => 'ssl',
        'smtp_port' => 465,
    ],
    'CCA' => [
        'smtp_host' => 'smtp.gmail.com',
        'smtp_username' => 'XXX@mail.fr',
        'smtp_password' => ' ',
        'smtp_secure' => 'ssl',
        'smtp_port' => 465,
    ],
    'MIND' => [
        'smtp_host' => 'smtp.gmail.com',
        'smtp_username' => 'XXX@mail.fr',
        'smtp_password' => ' ',
        'smtp_secure' => 'ssl',
        'smtp_port' => 465,
    ],
    'IMA' => [
        'smtp_host' => 'smtp.gmail.com',
        'smtp_username' => 'XXX@mail.fr',
        'smtp_password' => ' ',
        'smtp_secure' => 'ssl',
        'smtp_port' => 465,
    ],
    'IQ' => [
        'smtp_host' => 'smtp.gmail.com',
        'smtp_username' => 'XXX@mail.fr',
        'smtp_password' => ' ',
        'smtp_secure' => 'ssl',
        'smtp_port' => 465,
    ],
    'RES' => [
        'smtp_host' => 'smtp.gmail.com',
        'smtp_username' => 'XXX@mail.fr',
        'smtp_password' => ' ',
        'smtp_secure' => 'ssl',
        'smtp_port' => 465,
    ],
    'SAR' => [
        'smtp_host' => 'smtp.gmail.com',
        'smtp_username' => 'XXX@mail.fr',
        'smtp_password' => ' ',
        'smtp_secure' => 'ssl',
        'smtp_port' => 465,
    ],
    'SESI' =>[
        'smtp_host' => 'smtp.gmail.com',
        'smtp_username' => 'XXX@mail.fr',
        'smtp_password' => ' ',
        'smtp_secure' => 'ssl',
        'smtp_port' => 465,
    ],
    'STL' => [
        'smtp_host' => 'smtp.gmail.com',
        'smtp_username' => 'XXX@mail.fr',
        'smtp_password' => ' ',
        'smtp_secure' => 'ssl',
        'smtp_port' => 465,
    ],
];
